spring.application.name=bff-emergencia
server.port=1019
# Configuración Resilience4j - Circuit Breaker

#usuario-service

resilience4j.circuitbreaker.instances.usuario-service.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.usuario-service.slidingWindowSize=10
resilience4j.circuitbreaker.instances.usuario-service.failureRateThreshold=50.0
resilience4j.circuitbreaker.instances.usuario-service.waitDurationInOpenState=10000
resilience4j.circuitbreaker.instances.usuario-service.permittedNumberOfCallsInHalfOpenState=3

#reporte-service

resilience4j.circuitbreaker.instances.reporte-service.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.reporte-service.slidingWindowSize=10
resilience4j.circuitbreaker.instances.reporte-service.failureRateThreshold=50.0
resilience4j.circuitbreaker.instances.reporte-service.waitDurationInOpenState=10000
resilience4j.circuitbreaker.instances.reporte-service.permittedNumberOfCallsInHalfOpenState=3

# geo-service

resilience4j.circuitbreaker.instances.geo-service.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.geo-service.slidingWindowSize=10
resilience4j.circuitbreaker.instances.geo-service.failureRateThreshold=50.0
resilience4j.circuitbreaker.instances.geo-service.waitDurationInOpenState=10000
resilience4j.circuitbreaker.instances.geo-service.permittedNumberOfCallsInHalfOpenState=3


# notificacion-service

resilience4j.circuitbreaker.instances.notificacion-service.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.notificacion-service.slidingWindowSize=10
resilience4j.circuitbreaker.instances.notificacion-service.failureRateThreshold=50.0
resilience4j.circuitbreaker.instances.notificacion-service.waitDurationInOpenState=10000
resilience4j.circuitbreaker.instances.notificacion-service.permittedNumberOfCallsInHalfOpenState=3


# riesgo-service

resilience4j.circuitbreaker.instances.riesgo-service.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.riesgo-service.slidingWindowSize=10
resilience4j.circuitbreaker.instances.riesgo-service.failureRateThreshold=50.0
resilience4j.circuitbreaker.instances.riesgo-service.waitDurationInOpenState=10000
resilience4j.circuitbreaker.instances.riesgo-service.permittedNumberOfCallsInHalfOpenState=3


# brigada-service

resilience4j.circuitbreaker.instances.brigada-service.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.brigada-service.slidingWindowSize=10
resilience4j.circuitbreaker.instances.brigada-service.failureRateThreshold=50.0
resilience4j.circuitbreaker.instances.brigada-service.waitDurationInOpenState=10000
resilience4j.circuitbreaker.instances.brigada-service.permittedNumberOfCallsInHalfOpenState=3